# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - go mod tidy
    - make build-ui
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -v
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/drewhammond/chefbrowser/internal/common/version.version={{ .Version }}
      - -X github.com/drewhammond/chefbrowser/internal/common/version.commitHash={{ .Commit }}
      - -X github.com/drewhammond/chefbrowser/internal/common/version.date={{ .CommitDate }}
release:
  draft: true
  replace_existing_draft: true
  prerelease: auto
  mode: append
archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
dockers:
  - image_templates:
      - "drewhammond/chefbrowser:{{ .Tag }}"
      - "drewhammond/chefbrowser:latest"
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
