name: backend-test
on:
  push:
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - 'Makefile'
      - '.github/workflows/backend-test.yml'
      - 'ui/templates/**'
      - 'ui/embed.go'
  pull_request:
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - 'Makefile'
      - '.github/workflows/backend-test.yml'
      - 'ui/templates/**'
      - 'ui/embed.go'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24.4'
          cache: true
          cache-dependency-path: go.sum
      - name: Install dependencies
        run: go mod download
      - name: Build Backend
        run: |
          go build -v ./...
      - name: Test
        run: go test -v ./...