on:
  push:
    branches:
      - 212-fix-docker
  workflow_call:
    inputs:
      push:
        description: Should the images be pushed
        default: true
        required: false
        type: boolean
      version:
        description: The version used when tagging the image
        default: 'dev'
        required: false
        type: string
jobs:
  build_and_push_images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      RELEASE_VERSION: "${{ github.event.release.tag_name }}"
      DOCKERHUB_REPO: "drewhammond/chefbrowser"
      GHCR_REPO: "ghcr.io/drewhammond/chefbrowser"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ inputs.push }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        if: ${{ inputs.push }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push images
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          push: ${{ inputs.push }}
          tags: |
            ${{ env.DOCKERHUB_REPO }}:${{ inputs.version }}
            ${{ env.GHCR_REPO }}:${{ inputs.version }}
          cache-from: type=gha
          cache-to: type=gha
