name: "Build Images"
on:
  push:
    branches:
      - 212-fix-docker

  # FIXME: these variables don't seem to work at all
  workflow_call:
    inputs:
      push:
        description: 'Should the images be pushed'
        default: false
        required: false
        type: boolean
      version:
        description: 'The version used when tagging the image'
        default: 'dev'
        required: false
        type: string
jobs:
  build_and_push_images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      RELEASE_VERSION: "${{ github.event.release.tag_name }}"
      DOCKERHUB_REPO: "drewhammond/chefbrowser"
      GHCR_REPO: "ghcr.io/drewhammond/chefbrowser"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.DOCKERHUB_REPO }}
            ${{ env.GHCR_REPO }}

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push images
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          tags: |
            ${{ env.DOCKERHUB_REPO }}:${{ env.RELEASE_VERSION }}
            ${{ env.DOCKERHUB_REPO }}:latest
            ${{ env.GHCR_REPO }}:${{ env.RELEASE_VERSION }}
            ${{ env.GHCR_REPO }}:latest
          cache-from: type=gha
          cache-to: type=gha
