name: go-test
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.2'
          cache: true
          cache-dependency-path: go.sum
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - name: Install dependencies
        run: go get .
      - name: Build UI
        working-directory: ./ui
        run: |
          npm ci
          npm run build
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...
