name: go-test
on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.5'
          cache: true
          cache-dependency-path: go.sum
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: ui/yarn.lock
      - name: Install dependencies
        run: go mod download
      - name: Build UI
        working-directory: ./ui
        run: |
          yarn install --frozen-lockfile
          yarn run build
      - name: Build Backend
        run: |
          go build -v ./...
      - name: Test
        run: go test -v ./...
