name: go-test
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.20
          cache: true
          cache-dependency-path: go.sum
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: ui/package-lock.json
      - name: Install dependencies
        run: go get .
      - name: Build UI
        working-directory: ./ui
        run: |
          npm ci
          npm run build
      - name: Build Backend
        run: |
          go generate ./...
          go build -v ./...
      - name: Test
        run: go test -v ./...
